steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/leafilms-pitch:latest'
      - '.'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/leafilms-pitch:latest']

images:
  - 'gcr.io/$PROJECT_ID/leafilms-pitch:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _NEXT_PUBLIC_SUPABASE_URL: 'https://fmwcrgfxmlgfnsinnuyy.supabase.co'
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtd2NyZ2Z4bWxnZm5zaW5udXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MDAxMjAsImV4cCI6MjA3ODE3NjEyMH0.6Q7wEUtSfOnCJ4OHWA1VT0ma0ya7DjcZQxCqPWMCMnE'

