export const C = {
  bg:       'var(--admin-bg)',
  sidebar:  'var(--admin-sidebar)',
  surface:  'var(--admin-surface)',
  surface2: 'var(--admin-surface2)',
  border:   'var(--admin-border)',
  text:     'var(--admin-text)',
  text2:    'var(--admin-text2)',
  text3:    'var(--admin-text3)',
  accent:   'var(--admin-accent)',
  accentBg: 'var(--admin-accent-bg)',
  danger:   'var(--admin-danger)',
  success:  'var(--admin-success)',
  warning:  'var(--admin-warning)',
  hoverBorder: 'var(--admin-hover-border)',
}
