// Delt no/en-ordbok for hele den offentlige seleksjonsflyten (/s: PIN, galleri,
// albumoversikt, album, gjennomgang). Språket arves fra prosjektet server-side
// (lib/customer-language.ts) og sendes inn som prop til klientkomponentene.

export type SelectionLanguage = 'no' | 'en'

export const SELECTION_STRINGS = {
  no: {
    photoSelection: 'Bildeseleksjon',
    enterPin: 'Skriv inn PIN-koden du mottok',
    verifying: 'Verifiserer...',
    locked: 'Låst',
    openGallery: 'Åpne galleri',
    wrongPin: 'Feil PIN',
    tooManyAttempts: (mins: number) => `For mange forsøk. Prøv igjen om ${mins} min.`,
    selectedOf: (n: number, target: number | null) =>
      target != null ? `${n} av ${target} valgt` : `${n} valgt`,
    overWarning: (n: number, target: number) =>
      `Du har valgt ${n} av ${target} avtalte bilder — bilder utover avtalen kan medføre tillegg.`,
    viewAllSelected: (n: number) => `Se alle valgte (${n})`,
    reviewBeforeSubmit: 'Gjennomgå før innsending',
    submitSelection: (n: number) => `Send inn utvalg (${n})`,
    submittedBadge: 'Sendt inn',
    submittedCheck: '✓ Innsendt',
    videoLabel: 'Video',
    commentCount: (n: number) => `${n} kommentar${n !== 1 ? 'er' : ''}`,
    imageCount: (n: number) => `${n} bilder`,
    selectedBadge: (n: number) => `${n} valgt`,
    submittedTitle: '✓ Utvalget er sendt inn',
    submittedBody: (n: number) => `Vi har mottatt dine ${n} valgte bilder og tar kontakt.`,
    selectedShort: '✓ Valgt',
    select: 'Velg',
    selectThisPhoto: 'Velg dette bildet',
    tapToCommentLine1: 'Trykk på et bilde',
    tapToCommentLine2: 'for å se og legge til kommentarer',
    noCommentYet: 'Ingen kommentar enda',
    writeComment: 'Skriv en kommentar...',
    writeCommentToPhotographer: 'Skriv en kommentar til fotografen...',
    yourNameOptional: 'Ditt navn (valgfritt)',
    confirmTitle: 'Send inn utvalg?',
    confirmOverWarning: (n: number, over: number) =>
      `Du har valgt ${n} bilder — ${over} over avtalt antall. Dette kan medføre tilleggskostnad.`,
    confirmBody: (n: number) =>
      `Du sender inn ${n} ${n === 1 ? 'bilde' : 'bilder'}. Etter innsending kan ikke utvalget endres uten at vi åpner det på nytt.`,
    confirmBodyAlbum: (n: number) =>
      `Du sender inn ${n} ${n === 1 ? 'bilde' : 'bilder'}. Dette kan ikke endres etterpå.`,
    cancel: 'Avbryt',
    sending: 'Sender...',
    confirm: 'Bekreft',
    confirmAndSubmit: 'Bekreft og send inn',
    cannotChangeAfter: 'Kan ikke endres etter innsending',
    review: 'Gjennomgang',
    ofTargetAgreed: (target: number) => `av ${target} avtalte`,
    selectedWord: 'valgt',
    overAgreed: (n: number) => `${n} over avtalt antall — kan medføre tillegg`,
    noPhotosSelected: 'Ingen bilder er valgt enda.',
    backToOverview: 'Gå tilbake til oversikten',
    somethingWentWrong: 'Noe gikk galt. Prøv igjen.',
    thanksReceived: 'Takk! Ditt utvalg er mottatt.',
    youSelected: (n: number) => `Du valgte ${n} ${n === 1 ? 'bilde' : 'bilder'}.`,
    goToReview: 'Gå til gjennomgang',
    backToOverviewTab: '← Oversikt',
    folders: 'Mapper',
    zoomLabel: 'Bildestørrelse',
    notReadyTitle: 'Galleriet er ikke klart ennå',
    notReadyBody: 'Vi kvalitetssikrer utvalget internt før det blir tilgjengelig. Prøv igjen litt senere.',
  },
  en: {
    photoSelection: 'Photo selection',
    enterPin: 'Enter the PIN code you received',
    verifying: 'Verifying...',
    locked: 'Locked',
    openGallery: 'Open gallery',
    wrongPin: 'Incorrect PIN',
    tooManyAttempts: (mins: number) => `Too many attempts. Try again in ${mins} min.`,
    selectedOf: (n: number, target: number | null) =>
      target != null ? `${n} of ${target} selected` : `${n} selected`,
    overWarning: (n: number, target: number) =>
      `You have selected ${n} of the ${target} agreed photos — photos beyond the agreement may incur an additional charge.`,
    viewAllSelected: (n: number) => `View all selected (${n})`,
    reviewBeforeSubmit: 'Review before submitting',
    submitSelection: (n: number) => `Submit selection (${n})`,
    submittedBadge: 'Submitted',
    submittedCheck: '✓ Submitted',
    videoLabel: 'Video',
    commentCount: (n: number) => `${n} comment${n !== 1 ? 's' : ''}`,
    imageCount: (n: number) => `${n} photos`,
    selectedBadge: (n: number) => `${n} selected`,
    submittedTitle: '✓ Selection submitted',
    submittedBody: (n: number) => `We have received your ${n} selected photos and will be in touch.`,
    selectedShort: '✓ Selected',
    select: 'Select',
    selectThisPhoto: 'Select this photo',
    tapToCommentLine1: 'Tap a photo',
    tapToCommentLine2: 'to view and add comments',
    noCommentYet: 'No comments yet',
    writeComment: 'Write a comment...',
    writeCommentToPhotographer: 'Write a comment to the photographer...',
    yourNameOptional: 'Your name (optional)',
    confirmTitle: 'Submit selection?',
    confirmOverWarning: (n: number, over: number) =>
      `You have selected ${n} photos — ${over} more than agreed. This may incur an additional charge.`,
    confirmBody: (n: number) =>
      `You are submitting ${n} photo${n === 1 ? '' : 's'}. After submission the selection cannot be changed unless we reopen it.`,
    confirmBodyAlbum: (n: number) =>
      `You are submitting ${n} photo${n === 1 ? '' : 's'}. This cannot be changed afterwards.`,
    cancel: 'Cancel',
    sending: 'Submitting...',
    confirm: 'Confirm',
    confirmAndSubmit: 'Confirm and submit',
    cannotChangeAfter: 'Cannot be changed after submission',
    review: 'Review',
    ofTargetAgreed: (target: number) => `of ${target} agreed`,
    selectedWord: 'selected',
    overAgreed: (n: number) => `${n} over the agreed number — may incur an additional charge`,
    noPhotosSelected: 'No photos selected yet.',
    backToOverview: 'Back to the overview',
    somethingWentWrong: 'Something went wrong. Please try again.',
    thanksReceived: 'Thank you! Your selection has been received.',
    youSelected: (n: number) => `You selected ${n} photo${n === 1 ? '' : 's'}.`,
    goToReview: 'Go to review',
    backToOverviewTab: '← Overview',
    folders: 'Folders',
    zoomLabel: 'Photo size',
    notReadyTitle: 'The gallery isn’t ready yet',
    notReadyBody: 'We’re doing an internal quality check on the selection before it becomes available. Please check back soon.',
  },
}

export type SelectionStrings = (typeof SELECTION_STRINGS)['no']
